app/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("", views.index_view),
	path("registration/", views.registration_view),
	path("recovery/", views.recovery_view),
	path("login/", views.login_view),
	path("logout/", views.logout_view),
	path("contests/", views.contest_list),
	path("question/<id>/", views.question_list),
	path("contests/<id>/", views.contest_detail),
	path("account/", views.account_detail),
	path("ranking/", views.ranking_list),
	path("submit_solution/", views.submit_solution),
]

contest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
]

admin.site.site_header = "IUBAT Beta Admin Panel"
admin.site.site_title = "IUBAT Beta Admin Panel"

app/models.py
from django.db import models
from django.contrib.auth.models import User


class Contest(models.Model):
	name = models.CharField(max_length=100)
	contest_date = models.DateTimeField()

	def __str__(self):
		return self.name

class Member(models.Model):
	is_judge = models.BooleanField(default=False)
	first_name = models.CharField(max_length=100, default='')
	last_name = models.CharField(max_length=100, default='')
	recovery_id = models.CharField(max_length=100, blank=True, null=True)
	password = models.CharField(max_length=100, blank=True, null=True)
	is_participant = models.BooleanField(default=False)
	user_id = models.CharField(max_length=8, default='')
	contest = models.ManyToManyField(Contest)
	point = models.FloatField(default=0)
	date_joined = models.DateTimeField(auto_now_add=True, blank=True, null=True)

	def __str__(self):
		return self.first_name + self.last_name

class Question(models.Model):
	body = models.TextField()
	name = models.CharField(max_length=100)
	input = models.TextField()
	output = models.TextField()
	samples = models.TextField()
	point = models.IntegerField()
	correct_ans = models.TextField()
	judge = models.ForeignKey(Member, on_delete=models.CASCADE)
	contest = models.ForeignKey(Contest, on_delete=models.CASCADE)

class Solution(models.Model):
	body = models.TextField()
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	participant = models.ForeignKey(Member, on_delete=models.CASCADE)

app/views.py
from django.shortcuts import render, redirect
from . import models
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages


def index_view(request):
	return redirect("/login/")


def registration_view(request):
	if request.method == "POST":
		try:
			user_check = user = models.Member.objects.get(user_id=request.POST["id"])
		except:
			user_check = None
		if user_check:
			messages.error(request, "User already exists!")
			return redirect("/registration/")
		elif request.POST["password1"] != request.POST["password2"]:
			messages.error(request, "Password did not match!")
			return redirect("/registration/")
		elif request.POST["id"][4] != '3':
			print(request.POST["id"][4])
			messages.error(request, "You're not from CSE department")
			return redirect("/registration/")
		else:
			print(request.POST)
			new_member = models.Member.objects.create(
				first_name=request.POST["f_name"],
				last_name=request.POST["l_name"],
				user_id=request.POST["id"],
				recovery_id=request.POST["recovery_id"]
			)
			print(new_member.password)
			new_member.password = request.POST["password1"]
			if request.POST["user_type"] == "Participants":
				new_member.is_participant = 1
			elif request.POST["user_type"] == "Judge":
				new_member.is_judge = 1
			new_member.save()
			return redirect("/login/")

	return render(request, "contest/registration.html", {})


def login_view(request):
	if request.method == "POST":
		try:
			user = models.Member.objects.get(user_id=request.POST["id"])
		except:
			user = None
		if user and user.password == request.POST["password"]:
			request.session["user_id"] = user.user_id
		else:
			messages.error(request, "Login error!")
			return redirect("/login/")

	return render(request, "contest/login.html", {})


def logout_view(request):
	del request.session["user_id"]
	return redirect("/login/")

def recovery_view(request):
	if request.method == "POST":
		try:
			user = models.Member.objects.get(recovery_id=request.POST["recovery_id"])
			messages.success(request, "Your password is: " + user.password)
		except:
			messages.error(request, "Id not found!")
	return render(request, "contest/recovery.html", {})


def contest_list(request):
	contests = models.Contest.objects.all()
	return render(request, "contest/contestlist.html", {"contests": contests})


def question_list(request, id):
	question = models.Question.objects.get(pk=id)
	return render(request, "contest/question_detail.html", {"question": question})


def contest_detail(request, id):
	contest = models.Contest.objects.get(id=id)
	questions = models.Question.objects.filter(contest_id=contest.id)
	return render(request, "contest/contest_detail.html", {"questions": questions, "contest_name": contest.name})

def account_detail(request):
	user = models.Member.objects.get(user_id=request.session["user_id"])
	contests = user.contest.values_list("pk", flat=True)
	solutions = models.Solution.objects.filter(participant_id=user.id)
	print()
	return render(request, "contest/account_detail.html", {"user": user})

def ranking_list(request):
	users = models.Member.objects.all().order_by("point")
	return render(request, "contest/ranking_list.html", {"users": users})

def submit_solution(request):
	question = models.Question.objects.get(pk=request.POST["question_id"])
	participant = models.Member.objects.get(user_id=request.session["user_id"])
	try:
		solution_check = models.Solution.objects.get(question_id=question.id, participant_id=participant.id)
	except:
		solution_check = None

	if solution_check:
		messages.error(request, "Sorry, you already submitted the solution!")
		return redirect(request.META["HTTP_REFERER"])

	if request.POST["solution"] != question.correct_ans:
		messages.error(request, "Sorry, your solution is not correct!")
		return redirect(request.META["HTTP_REFERER"])

	elif request.POST["solution"] != question.correct_ans:
		messages.error(request, "Sorry, your solution is not correct!")
		return redirect(request.META["HTTP_REFERER"])
	else:
		solution = models.Solution.objects.create(
			question=question,
			participant=participant,
			body=request.POST["solution"]
		)
		participant.point += question.point
		participant.save()
		messages.success(request, "Your solution submitetd successfully")
		return redirect(request.META["HTTP_REFERER"])

app/templates/contest/Index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Programming Contest</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Website Logo</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="Index.html">Home</a></li>
      <li><a href="ContestList.html">Contest</a></li>
      <li><a href="problems.html">Problems</a></li>
      <li><a href="submissions.html">Submission</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="registration.html"><span class="glyphicon glyphicon-user"></span> Registration</a></li>
      <li><a href="Login.html"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
  
<div class="container">

</div>

</body>
</html>

app/templates/contest/Login.html
{% extends 'contest/base.html' %}

{% block content %}
<h2>Log In</h2>
{% for m in messages %}
<p style="color: #ff731e; font-weight: bold;">{{ m.message }}</p>
{% endfor %}
<form action="." method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id">ID:</label>
        <input type="number" name="id" class="form-control" id="" placeholder="Enter ID">
    </div>
    <div class="form-group">
        <label for="pwd">Password:</label>
        <input type="password" name="password" class="form-control" id="" placeholder="Enter password">
    </div>
    <div class="checkbox">
        <label><input type="checkbox"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-success">Login</button>
    <hr>
    <p>Or</p>
    <div><a href="/registration/">Create an account</a></div>
    <div><a href="/recovery/">Forgot password?</a></div>

</form>


{% endblock %}

app/templates/contest/account_detail.html
{% extends 'contest/base.html' %}

{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">Account Details: {{ user.user_id }}</div>
  <div class="panel-body">
      <h3>First Name: {{ user.first_name }}</h3>
      <hr>
      <h3>Last Name: {{ user.last_name }}</h3>
      <hr>
      <h3>ID: {{ user.user_id }}</h3>
      <hr>
      <h3>Total Points: {{ user.point }}</h3>
      <hr>
      <h3>Total Contests: {{ user.contest.count }}</h3>
      <hr>
      <h3>Total Solutions: {{ user.solution_set.count }}</h3>
  </div>
</div>
{% endblock %}

app/templates/contest/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">IUBAT β</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="/contests/">Contests</a></li>
                    <li><a href="/ranking/">Ranking</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if not request.session.user_id %}
                    <li><a href="/registration/"><span class="glyphicon glyphicon-user"></span> Registration</a></li>
                    <li><a href="/login/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    {% else %}
                    <li><a href="/account/"><span class="glyphicon glyphicon-user"></span> Account</a></li>
                    <li><a href="/logout/"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}

        </div>

    </body>
</html>

app/templates/contest/contest_detail.html
{% extends 'contest/base.html' %}

{% block content %}

<h2 align="center">{{ contest_name }} - Problems List</h2>

<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Sl</th>
                <th>Name</th>
                <th>Point</th>
            </tr>
        </thead>
        <tbody>
            {% for q in questions %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="/question/{{ q.id }}/">{{ q.name }}</a></td>
                <td>{{ q.point }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>

{% endblock %}

app/templates/contest/contestlist.html
{% extends 'contest/base.html' %}

{% block content %}

<h2 align="center">Contest List</h2>

<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Sl</th>
                <th>Name</th>
                <th>Date</th>
                <th>Status</th>
                <th>Total Questions</th>
            </tr>
        </thead>
        <tbody>
            {% for c in contests %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{{ c.id }}/">{{ c.name }}</a></td>
                <td>{{ c.contest_date }}</td>
                <td>A</td>
                <td>{{ c.question_set.count }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>

{% endblock %}

app/templates/contest/question_detail.html
{% extends 'contest/base.html' %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">Question Details: {{ user.user_id }}</div>
    <div class="panel-body">
        {% for m in messages %}
        <p style="color: #ff731e; font-weight: bold;">{{ m.message }}</p>
        <br>
        {% endfor %}
        <h3>Question Name: {{ question.name }}</h3>
        <br>
        <h5> {{ question.body }}</h5>
        <hr>
        <h3>Input</h3>
        <br>
        <h5> {{ question.input }}</h5>
        <hr>
        <h3>Output</h3>
        <br>
        <h5> {{ question.output }}</h5>
        <hr>
        <h3>Samples</h3>
        <br>
        <h5> {{ question.samples }}</h5>
        <hr>
        <h3>Submit Output Solution</h3>
        <br>
        <form action="/submit_solution/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            Output:
            <input type="text" name="solution">
            <br>
            <br>
            <input type="submit" class="btn btn-primary" value="Submit">
            <input type="hidden" name="question_id" value="{{ question.id }}">
        </form>

        <h3>Submit File Solution</h3>
        <br>
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="solution_file">
            <br>
            <input type="submit" class="btn btn-primary" value="Submit">
            <input type="hidden" name="question_id" value="{{ question.id }}">
        </form>
        <hr>

    </div>
</div>
{% endblock %}

app/templates/contest/ranking_list.html
{% extends 'contest/base.html' %}

{% block content %}

<h2 align="center">Ranking</h2>

<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Sl</th>
                <th>Name</th>
                <th>Point</th>
                <th>Total Contests</th>
                <th>Total Questions</th>
            </tr>
        </thead>
        <tbody>
            {% for u in users %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ u.first_name }} {{ u.last_name }}</td>
                <td>{{ u.point }}</td>
                <td>{{ u.contest.count }}</td>
                <td>{{ u.question_set.count }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>

{% endblock %}

app/templates/contest/recovery.html
{% extends 'contest/base.html' %}

{% block content %}
<h2>Recover password</h2>
{% for m in messages %}
<p style="color: #ff731e; font-weight: bold;">{{ m.message }}</p>
{% endfor %}
<form action="." method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id">Recovery ID:</label>
        <input type="text" name="recovery_id" class="form-control" id="" placeholder="Enter secret recovery ID">
    </div>

    <button type="submit" class="btn btn-success">Recover</button>

</form>

{% endblock %}

app/templates/contest/registration.html
{% extends 'contest/base.html' %}

{% block content %}
<h2>Registration</h2>
{% for m in messages %}
<p style="color: #ff731e; font-weight: bold;">{{ m.message }}</p>
{% endfor %}
<form action="." method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="FName">First Name:</label>
        <input type="text" name="f_name" class="form-control" id="" placeholder="First Name" required>
    </div>
    <div class="form-group">
        <label for="LName">Last Name:</label>
        <input type="text" name="l_name" class="form-control" id="" placeholder="Last Name" required>
    </div>
    <div class="form-group">
        <label for="email">Recovery ID:</label>
        <input type="text" name="recovery_id" class="form-control" id="" placeholder="Enter secret Id for recovery" required>
    </div>
    <div class="form-group">
        <label for="Id">Id:</label>
        <input type="text" name="id" class="form-control" id="" placeholder="Enter University ID" required>
    </div>
    <div class="form-group">
        <label for="pwd">Password:</label>
        <input type="password" name="password1" class="form-control" id="" placeholder="Enter password" required>
    </div>
    <div class="form-group">
        <label for="pwd">Confirm Password:</label>
        <input type="password" name="password2" class="form-control" id="" placeholder="Re-Enter password" required>
    </div>
    <div class="form-group">
        <label for="Usertype">User Type:</label>
        <select name="user_type" required>
            <option value="User">User</option>
            <option value="Judge">Judge</option>
            <option value="Participants">Participants</option>
        </select>
    </div>
    <button type="Registration" class="btn btn-success">Signup</button>
    <div>
        <a href="/login/">Already have an account</a>
    </div>
</form>

{% endblock %}